// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShareTracker.Infrastructure.Persistence;

#nullable disable

namespace ShareTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ShareTrackerDbContext))]
    [Migration("20260228125442_AddBrokerageFees")]
    partial class AddBrokerageFees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShareTracker.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("DateOfTrade")
                        .HasColumnType("date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("ExchangeRateApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForeignTrade")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NumberOfUnits")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("NumberOfUnitsSold")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trades");

                    b.HasDiscriminator<string>("AssetType").HasValue("Trade");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("ClerkUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HomeCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsForeignResident")
                        .HasColumnType("boolean");

                    b.HasKey("ClerkUserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.BondTrade", b =>
                {
                    b.HasBaseType("ShareTracker.Domain.Entities.Trade");

                    b.Property<string>("BondCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<decimal>("YieldPercent")
                        .HasColumnType("numeric(8,4)");

                    b.HasDiscriminator().HasValue("Bond");
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.CryptoTrade", b =>
                {
                    b.HasBaseType("ShareTracker.Domain.Entities.Trade");

                    b.Property<decimal?>("BrokerageFees")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CoinSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Network")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("Trades", t =>
                        {
                            t.Property("BrokerageFees")
                                .HasColumnName("CryptoTrade_BrokerageFees");
                        });

                    b.HasDiscriminator().HasValue("Crypto");
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.GoldTrade", b =>
                {
                    b.HasBaseType("ShareTracker.Domain.Entities.Trade");

                    b.Property<int>("PurityCarats")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasDiscriminator().HasValue("Gold");
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.PropertyTrade", b =>
                {
                    b.HasBaseType("ShareTracker.Domain.Entities.Trade");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasDiscriminator().HasValue("Property");
                });

            modelBuilder.Entity("ShareTracker.Domain.Entities.SharesTrade", b =>
                {
                    b.HasBaseType("ShareTracker.Domain.Entities.Trade");

                    b.Property<decimal?>("BrokerageFees")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasDiscriminator().HasValue("Shares");
                });
#pragma warning restore 612, 618
        }
    }
}
